### ISSUE TITLE
Export results of Ecuador: El Piedrero fixed on OSM

### ISSUE THREAD

**Issue by pabl-o-ce** [hyperknot/country-level-id#14]
Is already fixed on OSM the province of Guayas [ISO-2 EC-G]
adding El Piedrero that belongs to Guayas.

Can you please generate the geoJSON of Guayas to your export files repo

Thanks 🙂

**Comment by hyperknot** [comment]
Thanks for noting this. I've made the required changes to the repo which allows fixing this and I started a full reprocessing on my server. It should be ready in about an hour.

**Comment by pabl-o-ce** [comment]
your work is amazing thanks
