### ISSUE TITLE
Ecuador data miss a province

### ISSUE THREAD

**Issue by pabl-o-ce** [hyperknot/country-level-id#6]
Hi,
In Ecuador is missing a province and the names need some review.
How can a help to add this province "Provincia de Los Ríos" iso-2:EC-LR

**Comment by hyperknot** [comment]
Hi @pablocarreraest and thank for the report. I believe what is happening is that it's erroreous in ISO code both on OpenStreetMap and on Wikidata.

Can you edit the right ISO code in Wikidata?

https://www.wikidata.org/wiki/Q504260
and on OSM:
https://www.openstreetmap.org/relation/109248#map=8/-1.516/-78.138

I can do a reprocessing afterwards and it'll be fixed.

Also "Names need some review" can you explain more?

**Comment by hyperknot** [comment]
Actually I think it there as "Los Ríos", isn't that right?

**Comment by hyperknot** [comment]
I checked the official ISO database, "Los Ríos" is right as "EC-R". I believe everything is right, what is the problem?

**Comment by hyperknot** [comment]
https://www.iso.org/obp/ui/#iso:code:3166:EC

**Comment by pabl-o-ce** [comment]
sorry I made the wrong call (I see on mapbox thats why I create the issue).
Amazing work help me a lot to learn wit your json info.

An for the names of "wikipedia_id": "es:Imbabura (provincia)"
the name right is "wikipedia_id": "es:Provincia de Imbabura" and other need some review in the name how can I change that.

**Comment by hyperknot** [comment]
So wikipedia_id isn't really a name, it's a short URL for Wikipedia.

I think "es:Imbabura (provincia)" redirects to "es:Provincia_de_Imbabura", so it's not a big problem. If you feel one of them is wrong, you can edit them on Wikidata!
